mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
spring:
  datasource:
    url: jdbc:mysql://rm-wz9v6ey1y446me9055o.mysql.rds.aliyuncs.com/seckill?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: "@qwe123456"
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    club:
      lightingsummer:
        seckill:
          seckill: debug
